run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/c0deZ3R0/go-sync-kit)
    skip-generated: true
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/c0deZ3R0/go-sync-kit
  
  golint:
    min-confidence: 0.8
  
  govet:
    check-shadowing: true
    enable-all: true
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        arguments:
          - "disableStutteringCheck"

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - cyclop           # Covered by gocyclo
    - funlen           # Too restrictive for some valid cases
    - gochecknoglobals # Some globals are necessary
    - godox            # Allow TODO/FIXME comments
    - lll              # Line length is handled by gofmt
    - nlreturn         # Too opinionated
    - wsl              # Too restrictive formatting

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - goconst
    
    # Exclude specific issues
    - text: "Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    
    # Exclude shadow checking for err variables (common Go pattern)
    - text: "shadow: declaration of \"err\" shadows declaration"
      linters:
        - govet
    
    # Allow dot imports in test files
    - path: _test\.go
      text: "dot imports"
      linters:
        - revive
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
